### PR TITLE
Sliding door

### PR DESCRIPTION
**Pull request by Selfrom**
Added a SlidingDoor script which takes a door (GameObject), a direction(with magnitude) (Vector3), and a time to open (float).

When calling Open(), the door moves to the closed location, which is a distance away proportional to its size in the direction specified. (If x=0, y=1, z=0, the closed location is above the current location by the height of the door.)

When calling Close(), the door moves to the open location, which is the original location of the door.

Each movement takes an amount of time proportional to the distance needed to travel. (If going from a fully closed position to a fully open position, it should take the specified time to open.) Time to close is the same as time to open.

### CODE REVIEW

**Comment by Selfrom** [comment]
Will probably want to remove the Update() function that was included for testing/demo purposes only.

**Review by BUNN1E5 — CHANGES_REQUESTED** [review]
Looks good just change Remove the Update and it's ready to go

**Comment by Selfrom** [comment]
Removed the Update()

**Review by BUNN1E5 — APPROVED** [review]
Looks good

**Pull request merged**
