### PR TITLE
Player singleton, player prefab and combined work scene

### PR DESCRIPTION
**Pull request by Kainkun**
made a scene that combines some peoples work like player movement and shooting
made a player prefab for people to use easily
player also now has a player-manager with a singleton and a reference to other scripts the player relies on

### CODE REVIEW

**Review by BUNN1E5 — APPROVED** [review]
Looks good to me, It's just not my favorite singleton pattern

**Comment by Selfrom** [comment]
@BUNN1E5 Why is it not your favorite singleton pattern?

**Comment by Selfrom** [comment]
@Kainkun I was told to make sure to have DontDestroyOnLoad() in order to persist across scenes. Is this necessary?

**Comment by Kainkun** [comment]
@Selfrom are you talking about my work on the player manager? I'm not sure what you're talking about or why you're commenting on this pull request. What were you told to have DontDestroyOnLoad() for?

**Pull request merged**
